### ISSUE TITLE
Example is indented incorrectly

### ISSUE THREAD

**Issue by derrickburns** [fluxcd/flux-recv#7]
```
secretGenerator:
- name: fluxrecv-config
  files:
  - github.key
  - fluxrecv.yaml
generatorOptions:
  disableNameSuffixHash: true
```
