### ISSUE TITLE
Container port is missing from spec

### ISSUE THREAD

**Issue by derrickburns** [fluxcd/flux-recv#8]
```
      - name: recv
        image: fluxcd/flux-recv:0.2.0
        imagePullPolicy: IfNotPresent
        args:
        - --config=/etc/fluxrecv/fluxrecv.yaml
        ports:
        - containerPort: 8080
```
